name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - stock-14

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 g++-multilib libxml2-utils bzip2 libbz2-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make libssl-dev bc libc6-dev-i386 lib32ncurses-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 cpio kmod dwarves libelf-dev
        sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
        sudo apt-get install -y gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf

    - name: Set swap
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        swapon --show

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILER_ARM32=arm-linux-gnueabihf-
        bash kramel.sh

    - name: Upload Kernel ZIP
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zip
        path: out
