name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - stock-14

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl ccache flex bison build-essential zip libssl-dev bc python3 cpio kmod libelf-dev lz4 unzip

    - name: Set swap
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        swapon --show

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILER_ARM32=arm-linux-gnueabihf-
        export VERSION=4.19.157
        kver=1 zipn=Nethunter-a23-4.19.157 bash kramel.sh img mkzip

    - name: Upload Kernel ZIP
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zip
        path: out
